### ISSUE TITLE
1.6.9 broke Achtuur Core

### ISSUE THREAD

**Issue by Atulin** [Achtuur/StardewMods#7]
```
[SMAPI] Launching mods...
[AchtuurCore] Mod crashed on entry and might not work correctly. Technical details:
SContentLoadException: AchtuurCore failed loading content asset 'LooseSprites/buildingPlacementTiles' from the game content.
 ---> Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found.
 ---> FileNotFoundException: Could not find file 'E:\Games\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\buildingPlacementTiles.xnb'.
File name: 'E:\Games\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\buildingPlacementTiles.xnb'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Xna.Framework.TitleContainer.PlatformOpenStream(String safeName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\TitleContainer.Desktop.cs:line 29
   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\TitleContainer.cs:line 37
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 276
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 289
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 319
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 255
   at StardewModdingAPI.Framework.ContentManagers.BaseContentManager.RawLoad[T](IAssetName assetName, Boolean useCache) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/BaseContentManager.cs:line 340
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.<>c__DisplayClass6_0`1.<LoadExact>b__0() in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/GameContentManager.cs:line 127
   at StardewModdingAPI.Framework.Utilities.ContextHash`1.Track[TResult](T key, Func`1 action) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/Utilities/ContextHash.cs:line 53
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.LoadExact[T](IAssetName assetName, Boolean useCache)
   at StardewModdingAPI.Framework.ContentManagers.BaseContentManager.LoadLocalized[T](IAssetName assetName, LanguageCode language, Boolean useCache) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/BaseContentManager.cs:line 154
   at StardewModdingAPI.Framework.ModHelpers.GameContentHelper.Load[T](IAssetName assetName) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ModHelpers/GameContentHelper.cs:line 91
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Framework.ModHelpers.GameContentHelper.Load[T](IAssetName assetName) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ModHelpers/GameContentHelper.cs:line 95
   at AchtuurCore.Framework.Overlay.LoadPlacementTileTexture() in C:\Users\Arthur\source\repos\StardewMods\AchtuurCore\Framework\Overlay.cs:line 244
   at AchtuurCore.ModEntry.Entry(IModHelper helper) in C:\Users\Arthur\source\repos\StardewMods\AchtuurCore\ModEntry.cs:line 39
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/SCore.cs:line 1855
```

**Comment by Achtuur** [comment]
fixed in 1.3.2 release on nexusmods. Please use nexusmods for bug reports, I'd like the repo to be more about the actual code
